# Generated by Django 4.2.2 on 2024-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='image',
            field=models.ImageField(default='hello', upload_to='images/'),
            preserve_default=False,
        ),
    ]
