# Generated by Django 4.2.2 on 2024-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_postjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='description',
            field=models.TextField(default='hhhhhhh'),
            preserve_default=False,
        ),
    ]
