# Generated by Django 4.2.2 on 2024-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_postjob_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='jobType',
            field=models.CharField(default='hiii', max_length=255),
            preserve_default=False,
        ),
    ]
