# Generated by Django 5.0.1 on 2024-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_postjob_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='url',
            field=models.URLField(default='https://google.com', max_length=1500),
            preserve_default=False,
        ),
    ]
