# Generated by Django 5.0.1 on 2024-02-09 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_postjob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjob',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
