# Generated by Django 5.0.1 on 2024-03-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='postjob',
            name='jobLocationType',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=255),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='jobType',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('contract', 'Contract'), ('intership', 'Internship'), ('freelance', 'Freelance')], default='fulltime', max_length=255),
        ),
    ]
