# Generated by Django 5.0.1 on 2024-03-05 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_postjob_createdat_remove_postjob_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
